name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.2
  flutter_dotenv: ^5.0.2
  flutter_redux: ^0.10.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  redux_epics: ^0.15.1 
  redux: ^5.0.0 
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - .env
